### ISSUE TITLE
Crash with Allure 

### ISSUE THREAD

**Issue by CrankySupertoon** [kyrptonaught/DiggusMaximus#9] opened 2020-02-24 17:46 UTC
https://pastebin.com/p3BQdPcP

**Comment by CrankySupertoon** [comment] 2020-02-24 17:49
Cross Posted to Allure's Issue tracker they dont have (curseforge comments)

https://www.curseforge.com/minecraft/mc-mods/allure?comment=86

**Comment by kyrptonaught** [comment] 2020-02-24 17:49
See: https://github.com/kyrptonaught/DiggusMaximus/issues/8

Allure is not using mixins in a way that makes it compatible with other mods. The issue is on their end. I have tried reaching out to them but no response heard back

**Comment by kyrptonaught** [comment] 2020-03-31 18:48
This should be resolved with 1.2.8

**Closed** 2020-06-13 20:57 UTC
